---
- name: playbook to provision most of the MoodleBox
  hosts: all
  vars:
    ansible_user: 'root'
  become: 'true'

  vars_files:
    - default.config.yml

  pre_tasks:
    - debug:
        msg: 'Beginning of build: {{ lookup("pipe", "date +%Y-%m-%dT%H:%M:%S%z") }}'

    - name: set fact with build start timestamp
      set_fact:
        build_start: '{{ lookup("pipe", "date +%s") }}'

    - name: include customised variables
      include_vars: '{{ item }}'
      with_fileglob:
        - config.yml

  post_tasks:
    - debug:
        msg:
          - 'End of build: {{ lookup("pipe", "date +%Y-%m-%dT%H:%M:%S%z") }}'
          - 'Build duration: {{ lookup("pipe", "date +%s")|int - build_start|int }} s'

  roles:   

    - cron

    - adminer

    # - cert

    - cleanup
