---
- name: install packages
  apt:
    pkg: '{{ moodlebox_install_packages }}'
    state: 'present'
    update_cache: 'yes'
    autoremove: 'yes'
  when: 'moodlebox_install_packages is defined'
  register: packages_installed
  until: packages_installed is succeeded
