---

- include_tasks: install_prereqs.yml

- include_tasks: install_mariadb.yml

- include_tasks: uninstall_moodle.yml
  when: moodlebox_uninstall_moodle |bool

- include_tasks: install_moodle.yml
  when: moodlebox_uninstall_moodle |bool

- include_tasks: install_nginx.yml

- include_tasks: install_extras.yml

- include_tasks: cleanup.yml
