---

- name: configure MariaDB root password
  debconf:
    name: 'mariadb-server'
    question: '{{ item }}'
    vtype: 'password'
    value: '{{ moodlebox_db_root_password }}'
  with_items:
    - 'mysql-server/root_password'
    - 'mysql-server/root_password_again'
  register: configure_mariadb_install

- name: install MariaDB
  apt:
    pkg: 'mariadb-server'
    state: 'present'
  when: configure_mariadb_install is successful
  register: install_mariadb
  until: install_mariadb is succeeded

- name: install python-mysqldb
  apt:
    pkg: 'python-mysqldb'
    state: 'present'
  register: py_mysql_installed
  until: py_mysql_installed is succeeded

- name: add '{{ moodlebox_db_username }}' MariaDB user with all privileges
  mysql_user:
    name: '{{ moodlebox_db_username }}'
    host: 'localhost'
    password: '{{ moodlebox_db_password }}'
    priv: '*.*:ALL,GRANT'
    state: 'present'
  no_log: 'true'

- name: update MariaDB settings
  template:
    src: '50-server.cnf.j2'
    dest: '/etc/mysql/mariadb.conf.d/50-server.cnf'
    owner: "{{ database_user }}"
    group: "{{ database_user }}"
    mode: '0644'

- name: restart MariaDB database
  systemd:
    name: 'mariadb'
    state: 'restarted'
